# CRAWLER PARAMETERS
DEFAULT_MIN_PAGES = 200
DEFAULT_TOPIC = "tin-moi"
DEFAULT_MAX_ARTICLE_AGE_DAYS = 4

DEFAULT_ARTICLE_OUTPUT_FP = "result/articles.csv"
DEFAULT_CACHE_DB = "result/cached_urls.db"

# NER PARAMETERS
DEFAULT_MAX_ENTITIES = 50
DEFAULT_NER_OUTPUT_FP = "result/entities.csv"